import { useEffect, useState } from 'react';
import { Copy, ExternalLink, KeyRound, Link2Off, Plus, RefreshCw } from 'lucide-react';
import { api, ApiError } from '../lib/api';
import { formatDateTime } from '../lib/format';
import { Badge, Modal, useToast } from './ui';

type Acesso = { id: number; criado_em: string; expira_em: string | null; ultimo_acesso_em: string | null; acessos: number; status: 'ativo' | 'expirado' | 'revogado' };
export default function PortalAccessModal({ cliente, onClose }: { cliente: Record<string, any> | null; onClose: () => void }) {
  const toast = useToast(); const [acessos, setAcessos] = useState<Acesso[]>([]); const [validade, setValidade] = useState(90); const [novoLink, setNovoLink] = useState(''); const [busy, setBusy] = useState(false); const [erro, setErro] = useState('');
  async function load() { if (!cliente) return; setBusy(true); setErro(''); try { const d = await api.get<{ acessos: Acesso[] }>(`/clientes/${cliente.id}/portal-acessos`); setAcessos(d.acessos); } catch (e) { setErro(e instanceof ApiError ? e.message : 'Não foi possível carregar os acessos.'); } finally { setBusy(false); } }
  useEffect(() => { setNovoLink(''); load(); }, [cliente?.id]);
  async function gerar() { if (!cliente) return; setBusy(true); try { const d = await api.post<{ url: string }>(`/clientes/${cliente.id}/portal-acessos`, { validade_dias: validade }); setNovoLink(d.url); toast.success('Novo link seguro gerado. Ele será exibido apenas nesta tela.'); await load(); } catch (e) { setErro(e instanceof ApiError ? e.message : 'Não foi possível gerar o acesso.'); } finally { setBusy(false); } }
  async function revogar(id: number) { if (!cliente || !confirm('Revogar este acesso imediatamente?')) return; await api.post(`/clientes/${cliente.id}/portal-acessos/${id}/revogar`, {}); toast.success('Acesso revogado.'); await load(); }
  return <Modal open={!!cliente} onClose={onClose} title="Portal do cliente" subtitle={cliente?.nome} size="lg"><div className="space-y-4">
    <div className="rounded-xl border border-navy-100 bg-navy-50 p-4"><h3 className="text-sm font-bold text-navy-900">Gerar acesso pessoal</h3><p className="mt-1 text-xs text-slate-500">O token não pode ser recuperado depois. Se o cliente perder o link, gere outro e revogue o anterior.</p><div className="mt-3 flex flex-wrap gap-2"><select className="input w-36" value={validade} onChange={(e) => setValidade(Number(e.target.value))}><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={180}>180 dias</option><option value={365}>1 ano</option></select><button className="btn-accent" onClick={gerar} disabled={busy}><Plus className="h-4 w-4" /> Gerar link</button></div>{novoLink && <div className="mt-3 flex gap-2"><input className="input flex-1 font-mono text-xs" readOnly value={novoLink} onFocus={(e) => e.currentTarget.select()} /><button className="btn-secondary" onClick={() => { navigator.clipboard.writeText(novoLink); toast.success('Link copiado.'); }}><Copy className="h-4 w-4" /> Copiar</button><a className="btn-secondary" href={novoLink} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4" /></a></div>}</div>
    {erro && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{erro}</p>}
    <div className="card overflow-hidden !p-0"><div className="flex items-center justify-between border-b px-4 py-3"><h3 className="text-sm font-bold text-navy-900">Acessos emitidos</h3><button className="btn-icon" onClick={load}><RefreshCw className={`h-4 w-4 ${busy ? 'animate-spin' : ''}`} /></button></div>{!acessos.length ? <p className="py-8 text-center text-sm text-slate-400">Nenhum acesso emitido.</p> : <div className="overflow-x-auto"><table className="table text-xs"><thead><tr><th>Emitido</th><th>Expira</th><th>Último acesso</th><th>Acessos</th><th>Status</th><th></th></tr></thead><tbody>{acessos.map((a) => <tr key={a.id}><td>{formatDateTime(a.criado_em)}</td><td>{a.expira_em ? formatDateTime(a.expira_em) : 'Sem prazo'}</td><td>{a.ultimo_acesso_em ? formatDateTime(a.ultimo_acesso_em) : 'Nunca'}</td><td>{a.acessos}</td><td><Badge tone={a.status === 'ativo' ? 'green' : a.status === 'revogado' ? 'red' : 'amber'}>{a.status}</Badge></td><td>{a.status === 'ativo' && <button className="btn-icon hover:!bg-red-50 hover:!text-red-600" onClick={() => revogar(a.id)} title="Revogar"><Link2Off className="h-4 w-4" /></button>}</td></tr>)}</tbody></table></div>}</div>
    <p className="flex items-center gap-2 text-xs text-slate-400"><KeyRound className="h-3.5 w-3.5" /> Tokens são aleatórios, armazenados somente como hash e auditados.</p>
  </div></Modal>;
}
